<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>hxml</string>
  </array>
  <key>keyEquivalent</key>
  <string>^@H</string>
  <key>name</key>
  <string>Hxml</string>
  <key>foldingStartMarker</key>
  <string>--next</string>
  <key>foldingStopMarker</key>
  <string>\n\n</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>(-cpp?|-js|-as3|-swf-(header|version|lib)|-swf9?|-neko|-python|-php|-cs|-java|-xml|-x|-main|-lib|-D|-resource|-exclude|-v|-debug|-prompt|-cmd|-dce|--flash-strict|--no-traces|--flash-use-stage|--neko-source|--gen-hx-classes|-java-lib|-net-lib|--each|--next|--display|--no-output|--times|--no-inline|--no-opt|--php-front|--php-lib|--php-prefix|--remap|-help|--help|-java|-cs|--dead-code-elimination|--js-modern|--interp|--macro|--dce|--wait|--connect|--cwd|--help-defines|--run)</string>
      <key>name</key>
      <string>keyword.other.hxml</string>
    </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.actionscript</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(#).*$\n?</string>
      <key>name</key>
      <string>comment.line.number-sign.hxml</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.hxml</string>
  <key>uuid</key>
  <string>CB1B853A-C4C8-42C3-BA70-1B1605BE51C1</string>
</dict>
</plist>